services:
  stremthru:
    container_name: stremthru
    build:
      context: .
      dockerfile: ./Dockerfile
    image: muniftanjim/stremthru
    ports:
      - 7001:7001
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
  redis:
    image: redis:7-alpine
    ports:
      - 7002:6379
  postgres:
    image: postgres:16.6-alpine
    ports:
      - 7003:5432
    environment:
      POSTGRES_DB: stremthru
      POSTGRES_USER: stremthru
      POSTGRES_PASSWORD: stremthru
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
